language: node_js

node_js:
  - "0.11"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsnappy-dev
  - git clone git://github.com/ideawu/ssdb.git
  - cd ssdb
  - git checkout b62f018872352df9b8fdd69cd3b3a9a9cc8d3e2a
  - make
  - cd ..

before_script:
  - cd ssdb
  - ./ssdb-server ssdb.conf -d
  - cd ..

after_script:
  - killall -w ssdb-server
  - rm -rf ssdb/var/*

script:
  - npm test
